name: spotifynew
description: create Spotify UI using Flutter



publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_holo_date_picker: ^0.2.1
  page_view_indicators: ^1.3.2
  url_launcher: ^5.7.2
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/


